Repository w3c/openscreenprotocol, pull requests merged in 2019-05, with the labels that each got.

#157 Update authentication CDDL message definitions
  messages_appendix.cddl
  messages_appendix.html
Labels: F2F, Security, v1-spec

#150 Add support for media streaming
  index.bs
  index.html
  messages_appendix.cddl
  messages_appendix.html
Labels: F2F

#170 Recommend zero-length QUIC connection IDs
  index.bs
Labels: v1-spec
